# Custom secret scanning patterns for vulnerable-node demo
# These catch hardcoded secrets that standard providers don't detect
# Showcases GitHub secret scanning's custom pattern feature

paths:
  - "**/*.js"
  - "**/*.json"
  - "**/*.yml"
  - "**/*.env"
